name: kuruk_saarthi
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # page_transition #
  page_transition: ^2.1.0

  # input field #
  pinput: ^5.0.0

  # animated loader
  flutter_spinkit: ^5.2.1

  #database
  sqflite: ^2.3.3+1
  path: ^1.9.0


  # Network call
  http: ^1.2.2

  # dependency inject
  get_it: ^7.7.0

  # state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  rxdart:

  # google font
  google_fonts: ^6.2.1

  # local storage
  flutter_secure_storage: ^9.2.2

  # dropdown
  dropdown_button2: ^2.3.9

  # svg image
  flutter_svg: ^2.0.10+1

  # bottom nav bar
  bottom_navy_bar: ^6.1.0

  # slider
  syncfusion_flutter_sliders: ^26.2.13

  # bar chart
  syncfusion_flutter_charts: ^26.2.14

  # other
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  equatable: ^2.0.5
  another_flushbar: ^1.12.30
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.8
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  intl: any
  # firebase notification
  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.3
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  permission_handler: ^11.3.1
  cloud_firestore: ^5.4.1
  flutter_udid: ^3.0.0
  flutter_local_notifications: ^17.2.2
  path_provider: ^2.0.11
  json_serializer: ^0.2.0
  jiffy: ^6.3.1
  share_plus: ^10.0.3
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.14.0
  image_cropper: ^8.0.2
  speech_to_text: ^7.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12


# The following section is specific to Flutter packages.
flutter:
  generate: true

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icon_img/
     - assets/banner.png
#     - assets/output.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Mona Sans
       fonts:
         - asset: assets/fonts/Mona-Sans.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
